import { lazy } from 'react'

export const coreWidgetMetaItems = {
  './editors/TextFieldWithLangEditor/meta.ts': (await import('./editors/TextFieldWithLangEditor/meta')).default,
  './editors/EditorJsEditor/meta.ts': (await import('./editors/EditorJsEditor/meta')).default,
  './editors/TextFieldEditor/meta.ts': (await import('./editors/TextFieldEditor/meta')).default,
  './editors/IconifyEditor/meta.ts': (await import('./editors/IconifyEditor/meta')).default,
  './editors/AutoCompleteEditor/meta.ts': (await import('./editors/AutoCompleteEditor/meta')).default,
  './editors/ColorEditor/meta.ts': (await import('./editors/ColorEditor/meta')).default,
  './editors/URIEditor/meta.ts': (await import('./editors/URIEditor/meta')).default,
  './editors/DetailsEditor/meta.ts': (await import('./editors/DetailsEditor/meta')).default,
  './editors/ShapeEditor/meta.ts': (await import('./editors/ShapeEditor/meta')).default,
  './editors/BooleanSelectEditor/meta.ts': (await import('./editors/BooleanSelectEditor/meta')).default,
  './editors/FileUploadEditor/meta.ts': (await import('./editors/FileUploadEditor/meta')).default,
  './editors/NumberFieldEditor/meta.ts': (await import('./editors/NumberFieldEditor/meta')).default,
  './editors/EnumSelectEditor/meta.ts': (await import('./editors/EnumSelectEditor/meta')).default,
  './editors/DatePickerEditor/meta.ts': (await import('./editors/DatePickerEditor/meta')).default,
  './facets/CountFacet/meta.ts': (await import('./facets/CountFacet/meta')).default,
  './facets/TextFieldFacet/meta.ts': (await import('./facets/TextFieldFacet/meta')).default,
  './facets/DateFacet/meta.ts': (await import('./facets/DateFacet/meta')).default,
  './lists/CommaList/meta.ts': (await import('./lists/CommaList/meta')).default,
  './lists/UnorderedList/meta.ts': (await import('./lists/UnorderedList/meta')).default,
  './lists/NaturalLanguageList/meta.ts': (await import('./lists/NaturalLanguageList/meta')).default,
  './viewers/DetailsViewer/meta.ts': (await import('./viewers/DetailsViewer/meta')).default,
  './viewers/ColorViewer/meta.ts': (await import('./viewers/ColorViewer/meta')).default,
  './viewers/ImageViewer/meta.ts': (await import('./viewers/ImageViewer/meta')).default,
  './viewers/LabelViewer/meta.ts': (await import('./viewers/LabelViewer/meta')).default,
  './viewers/IconifyViewer/meta.ts': (await import('./viewers/IconifyViewer/meta')).default,
  './viewers/URIViewer/meta.ts': (await import('./viewers/URIViewer/meta')).default,
  './viewers/LiteralViewer/meta.ts': (await import('./viewers/LiteralViewer/meta')).default,
}

export const coreWidgetComponents = {
  './editors/TextFieldWithLangEditor/index.tsx': lazy(() => import('./editors/TextFieldWithLangEditor/index')),
  './editors/EditorJsEditor/index.tsx': lazy(() => import('./editors/EditorJsEditor/index')),
  './editors/TextFieldEditor/index.tsx': lazy(() => import('./editors/TextFieldEditor/index')),
  './editors/IconifyEditor/index.tsx': lazy(() => import('./editors/IconifyEditor/index')),
  './editors/AutoCompleteEditor/index.tsx': lazy(() => import('./editors/AutoCompleteEditor/index')),
  './editors/ColorEditor/index.tsx': lazy(() => import('./editors/ColorEditor/index')),
  './editors/URIEditor/index.tsx': lazy(() => import('./editors/URIEditor/index')),
  './editors/DetailsEditor/index.tsx': lazy(() => import('./editors/DetailsEditor/index')),
  './editors/ShapeEditor/index.tsx': lazy(() => import('./editors/ShapeEditor/index')),
  './editors/BooleanSelectEditor/index.tsx': lazy(() => import('./editors/BooleanSelectEditor/index')),
  './editors/FileUploadEditor/index.tsx': lazy(() => import('./editors/FileUploadEditor/index')),
  './editors/NumberFieldEditor/index.tsx': lazy(() => import('./editors/NumberFieldEditor/index')),
  './editors/EnumSelectEditor/index.tsx': lazy(() => import('./editors/EnumSelectEditor/index')),
  './editors/DatePickerEditor/index.tsx': lazy(() => import('./editors/DatePickerEditor/index')),
  './facets/CountFacet/index.tsx': lazy(() => import('./facets/CountFacet/index')),
  './facets/TextFieldFacet/index.tsx': lazy(() => import('./facets/TextFieldFacet/index')),
  './facets/DateFacet/index.tsx': lazy(() => import('./facets/DateFacet/index')),
  './lists/CommaList/index.tsx': lazy(() => import('./lists/CommaList/index')),
  './lists/UnorderedList/index.tsx': lazy(() => import('./lists/UnorderedList/index')),
  './lists/NaturalLanguageList/index.tsx': lazy(() => import('./lists/NaturalLanguageList/index')),
  './viewers/DetailsViewer/index.tsx': lazy(() => import('./viewers/DetailsViewer/index')),
  './viewers/ColorViewer/index.tsx': lazy(() => import('./viewers/ColorViewer/index')),
  './viewers/ImageViewer/index.tsx': lazy(() => import('./viewers/ImageViewer/index')),
  './viewers/LabelViewer/index.tsx': lazy(() => import('./viewers/LabelViewer/index')),
  './viewers/IconifyViewer/index.tsx': lazy(() => import('./viewers/IconifyViewer/index')),
  './viewers/URIViewer/index.tsx': lazy(() => import('./viewers/URIViewer/index')),
  './viewers/LiteralViewer/index.tsx': lazy(() => import('./viewers/LiteralViewer/index')),
}

